defmodule Mixwave.Accounts.AnonymousUser do
  @moduledoc """
  An anonymous user — created on first visit, identified only by a
  signed session cookie. Idle users (no `last_active_at` activity for
  more than 24 hours) are reaped by `Mixwave.Accounts.Sweeper`.
  """
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  schema "anonymous_users" do
    field :display_name, :string
    field :last_active_at, :utc_datetime

    timestamps(type: :utc_datetime, updated_at: false)
  end

  @doc """
  Changeset for creating a fresh anonymous user. The display name is
  generated by `Mixwave.Accounts.NameGenerator`; callers should pass it
  in via attrs.
  """
  def creation_changeset(user, attrs) do
    user
    |> cast(attrs, [:display_name, :last_active_at])
    |> validate_required([:display_name])
    |> validate_length(:display_name, min: 1, max: 64)
  end

  @doc """
  Bumps `last_active_at`. Used by the `EnsureAnonUser` plug — debounced
  in the plug itself so we don't write on every request.
  """
  def touch_changeset(user, now) do
    change(user, last_active_at: now)
  end
end
