import Config

# To test multi-user from another machine on your LAN:
#   1. find this machine's LAN IP (e.g. `ip route get 1.1.1.1`)
#   2. start the server with DEV_LAN_HOST=<that-ip> mix phx.server
#   3. open http://<that-ip>:4000 from the other machine
# Without DEV_LAN_HOST set, everything stays on localhost.
dev_host = System.get_env("DEV_LAN_HOST") || "localhost"

config :live_vue, vite_host: "http://#{dev_host}:5173", ssr_module: LiveVue.SSR.ViteJS

# Default admin credentials for /admin in dev. Override via env vars
# (`ADMIN_USER` / `ADMIN_PASSWORD`) if you want non-defaults locally.
config :mixwave,
  admin_user: System.get_env("ADMIN_USER", "admin"),
  admin_password: System.get_env("ADMIN_PASSWORD", "dev")

# Configure your database
config :mixwave, Mixwave.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "mixwave_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :mixwave, MixwaveWeb.Endpoint,
  # Bind to all interfaces so other machines on the LAN can join the
  # studio for multi-user testing. (Loopback-only is the safer default
  # for normal Phoenix dev; we override because the whole point of
  # mixwave's v1 is multi-user.)
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "HjTTfSpdfgWOj15/3CxN54DfYqiyBJWvcMrzcqOq4wpfSjpGgRqo5buJXsVWwU1M",
  watchers: [vite: {PhoenixVite.Npm, :run, [:vite, ~w(dev)]}],
  static_url: [host: dev_host, port: 5173]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :mixwave, MixwaveWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/mixwave_web/router\.ex$"E,
      ~r"lib/mixwave_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :mixwave, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
